### ISSUE TITLE
editorial: reference not linkified

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#727] opened 2016-10-20 21:43 UTC
https://tools.ietf.org/html/draft-ietf-tls-tls13-17#section-4.4.1.1

The first RFC6066 in the above section is not linkified, but the second is. The first has an exclamation mark in the syntax. I don't know what this is for, so filing an issue rather than a PR to change.

**Comment by xiaoyinl** [comment] 2016-10-20 22:23
@davegarrett `{{!RFCxxx}}` means it is a normative reference [1]. But probably that's not the cause of this issue, since this syntax is used in many places in the draft.

[1] https://github.com/cabo/kramdown-rfc2629#references

**Comment by ekr** [comment] 2016-10-25 04:14
Based on @xiaoyinl's comments I am going to close this. Ultimately RFC-Ed can fix it

**Closed by ekr** 2016-10-25 04:14 UTC

**Comment by davegarrett** [comment] 2016-10-25 18:23
Thanks for the doc link. Maybe it's possible it's breaking because we're mixing this syntax and a manual list here? I don't know. Personally, I'd rather we just maintain the manual list and not bother with this syntax. It would've been good to use from the start, but we didn't.
